- configure file fixes from Prof. Ripley - added native routines registration
git-svn-id: https://svn.r-project.org/R-packages/trunk@3435 694ef91d-65df-0310-b7bb-92e67a308ead

diff --git a/SQLiteDF/configure b/SQLiteDF/configure
--- a/SQLiteDF/configure
+++ b/SQLiteDF/configure
@@ -7,6 +7,20 @@ if test ! -d src/SQLite; then
   (cd src/SQLite; mv src/sqliteInt.h src/sqliteInt.h.orig; sed -e 's/MAX_ATTACHED 10/MAX_ATTACHED 31/' src/sqliteInt.h.orig > src/sqliteInt.h)
 fi
 if test ! -f src/SQLite/Makefile; then
+: ${R_HOME=`R RHOME`}
+  if test -z "${R_HOME}"; then
+    echo "could not determine R_HOME"
+    exit 1
+  fi
+  CC=`${R_HOME}/bin/R CMD config CC`
+  # we need to force a PIC build of a static library
+  CFLAGS=`${R_HOME}/bin/R CMD config CFLAGS`
+  CPICFLAGS=`${R_HOME}/bin/R CMD config CPICFLAGS`
+  CFLAGS="${CFLAGS} ${CPICFLAGS}"
+  export CC CFLAGS
   (cd src/SQLite; ./configure --disable-shared)
 fi
 (cd src/SQLite; make)
+# we need to pick up the library containing fdatasync
+TLIBS=`sed -n -e'/^TLIBS =/p' src/SQLite/Makefile | sed -e's/^TLIBS = //' `
+sed -e "s/@TLIBS@/${TLIBS}/" src/Makevars.in > src/Makevars
